### ISSUE TITLE
Znamenko u current_consumption_price

### ISSUE THREAD

**Issue by me2d13** [nanogreencz/homeassistant-integrations#3]
Dobry den

Nemelo by tady https://github.com/nanogreencz/homeassistant-integrations/blob/master/custom_components/nanogreen/coordinator.py#L74 byt plus?
Teda ona dokumentace rika, ze je to "Tržní cena pro spotřebu po odečtení poplatku za služby obchodu ve výši 350 Kč/MWh bez DPH.", takze podle dokumentace je to ok. Ale u consumption price se tech 350Kc preci k trzni cene pricita, takze odecitat to asi nema smysl.
Podle meho nazoru by to chtelo opravit znamenko a tu vetu v dokumentaci...

**Comment by filipek92** [comment]
Ano, dneska jsem si toho také všiml, potvrzuji, že se mi to také zdá špatně.

Ještě jsem přemýšlel, že by stálo za to tam přidat i variantu s daní za elektřinu, případně distribuci, ta už se ale liší podle tarifu, a ten by se musel někde volit,

**Comment by ajsicek** [comment]
Chápu dobře že tohle odpoví na otázku proč je consumption_price menší než spot_price? to by asi být neměla že?
