### ISSUE TITLE
Průběh ceny zítra

### ISSUE THREAD

**Issue by mnagovicz** [nanogreencz/homeassistant-integrations#7]
Chtěl bych v apex card vidět i průběh ceny druhý den. nedaří se mi to přidat. V senzoru tyto atributy jsou (Tomorrow hourly prices) Poradíte mi?

**Comment by michalpulda** [comment]
Je popsáno zde: http://forum.nanogreen.cz/t/jak-pridat-spotove-ceny-do-home-assistent/18/7
